### ISSUE TITLE
User Is Not Authenticated When Clicking Log User Info Button

### ISSUE THREAD

**Issue by nsankaranarayanan** [ruben-ilciuc/custom-amplify-auth#1]
Hello Ruben,

I just downloaded your sample, setup my values in the .env file and it seems to be up and running.
I logged in with a valid user and clicked on the "Log user info" button and I get "Uncaught (in promise) The user is not authenticated".
What am I missing?

Thanks

Narayanan

**Comment by admin-golfdistrict-io** [comment]
Never mind. I figured it out. The user was not in the confirmed status. Once I changed the password via the console things seems to work.

**Comment by nsankaranarayanan** [comment]
Never mind. I figured it out. The user was not in the confirmed status. Once I changed the password via the console things seems to work.
